# Generated by Django 3.2.8 on 2021-10-27 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitriao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logradoro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=7)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPA', 'AP'), ('AMAZONAS', 'AM'), ('BAHIA', 'BA'), ('CEARA', 'CE'), ('DISTRITO FEDERAL', 'DF'), ('ESPIRITO SANTO', 'ES'), ('GOIAS', 'GO'), ('MARANHOA', 'MA'), ('MATO GROSSO', 'MT'), ('MATO GROSSO DO SUL', 'MS'), ('MINAS GERAIS', 'MG'), ('PARANA', 'PR'), ('PARAIBA', 'PB'), ('PARA', 'PA'), ('PERNAMBUCO', 'PE'), ('PIAUI', 'PI'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RIO DE JANEIRO', 'RJ'), ('RONDONIA', 'RD'), ('RORAIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SERGIPE', 'SE'), ('SAO PAULO', 'SP'), ('TOCANTINS', 'TO')], max_length=20)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_pessoas', models.IntegerField()),
                ('pets', models.BooleanField()),
                ('quantidade_pets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='82RkCUJ8oq', editable=False, max_length=10, unique=True)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('data_check_in', models.DateTimeField()),
                ('data_check_out', models.DateTimeField()),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anfitriao.hospede')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anfitriao.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('tarefa', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('limpeza', 'Limpeza'), ('manutecao', 'Manutenção')], default='', max_length=9)),
                ('anfitriao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='todos', to='anfitriao.anfitriao')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anfitriao.imovel')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anfitriao.reserva')),
            ],
        ),
    ]
